theme: jekyll-theme-hacker
logo: https://avatars0.githubusercontent.com/u/72337471
title: reactive-stack-js-oracle-poc
description: reactive-stack-js oracle poc
show_downloads: "false"
include:
  - "_*_.html"
  - "_*_.*.html"
plugins:
  - jemoji